spring.application.name=CloudShareApi

spring.data.mongodb.uri=${MONGODB_URI}

server.servlet.context-path=/api/v1.0
spring.data.mongodb.auto-index-creation=true

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

clerk.issuer=https://full-mule-12.clerk.accounts.dev
clerk.jwks-url=https://full-mule-12.clerk.accounts.dev/.well-known/jwks.json
clerk.webhook.secret=${CLERK_WEBHOOK_SECRET}

#file upload configuration
spring.servlet.multipart.max-file-size=150MB
spring.servlet.multipart.max-request-size=250MB

razorpay.api.key=rzp_test_TJnAtswgk0kYRH
razorpay.api.secret=${RAZORPAY_API_SECRET}

minio.endpoint=${MINIO_ENDPOINT:http://localhost:9000}
minio.access-key=${MINIO_ACCESS_KEY:cloudshare_admin}
minio.secret-key=${MINIO_SECRET_KEY:cloudshare_password}
minio.bucket-name=${MINIO_BUCKET_NAME:cloudshare-files}

server.port=${PORT:8080}