spring.application.name=CloudShareApi

spring.data.mongodb.uri=mongodb+srv://cloudshare_app:rishab1912@rishab.slmop8o.mongodb.net/CloudShare?appName=Rishab

server.servlet.context-path=/api/v1.0
spring.data.mongodb.auto-index-creation=true

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

clerk.issuer=https://full-mule-12.clerk.accounts.dev
clerk.jwks-url=https://full-mule-12.clerk.accounts.dev/.well-known/jwks.json
